[package]
name = "psdevbot-rust"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
lazy_static = "1.2.0"
htmlescape = "0.3.1"
regex = "1.1.0"
serde = "1.0.85"
serde_derive = "1.0.85"
showdown = "0.2.0"
tokio = { version = "0.1.14", features = ["async-await-preview"] }
warp = "0.1.11"
warp_github_webhook = "0.2.2"
