[package]
name = "psdevbot-rust"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"

[dependencies]
bytes = "0.4.11"
futures-preview = { version = "0.3.0-alpha.12", features = ["compat"] }
hex = "0.3.2"
hmac = "0.7.0"
htmlescape = "0.3.1"
serde = "1.0.85"
serde_derive = "1.0.85"
serde_json = "1.0.36"
sha-1 = "0.8.1"
showdown = "0.1.4"
tokio = { version = "0.1.14", features = ["async-await-preview"] }
warp = "0.1.11"
